### ISSUE TITLE
Issues in Version 1.0.9

### ISSUE THREAD

**Issue by bushramustafa** [codeforpakistan/HCAIs-Surveillance-App#89]
- [x] The list of surgeons does not show all the names
- [x] The following fields value disappeared when I re-opened the submitted form: Guardian Name, Guardian Contact, Guardian CNIC, Date of Readmission, Hardware Administered
- [x] Multiselect fields are not retaining their values when I update a submitted form.
- [x] When I load a submitted form - in the pathogen report step (step 12) if positive growth is selected the hidden fields that should be visible are not visible.
- [x] In the submitted forms the Days Left is not based on the date of the procedure or any other data present in the form. I think that these Days Left are calculated based on the created_at or updated_at date which is wrong. It should be based on the date of the procedure.

**Comment by mubassirhayat** [comment]
Adding my feedback as well.
